version: '3.1'

services:
    mysql_database:
        container_name: mysql_database
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "default"
        ports:
            - "3306:3306"
        networks:
            - mysql-compose-network
    
    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080
        networks:
            - mysql-compose-network


networks: 
    mysql-compose-network:
        driver: bridge